version: '3.4'
services:
  jbook:
    image: rub21/jbook:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/mnt
      # - $HOME/.aws:/root/.aws
      - $PWD/:/home/jovyan/work 
    ports:
      - '8888:8888'